apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- stackspin-zulip-override.yaml # no push notifications for now
  - stackspin-nextcloud-override.yaml
  - stackspin-nginx-ingress-override.yaml
  - stackspin-apps-custom.yaml
  - storageclass-retain.yaml
  - source-controller-patch.yaml
