apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stackspin
  name: stackspin-kratos-override
data:
  values.yaml: |
    kratos:
      emailTemplates:
        recovery:
          valid:
            subject: Passwortänderung für FTT Forensic Discovery Single Sign-On
            body: |-
              Hallo {{ .Identity.traits.name }},<br />
              <br />
              Bitte klicken Sie auf den folgenden Link, um Ihr Passwort für FTT Forensic Discovery zu ändern:<br />
              <br />
              <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a><br />
              <br />
              Der Link läuft in einer Stunde ab. Sollte er nicht mehr funktionieren, starten Sie einen neuen Kontowiederherstellungsprozess über folgenden Link:<br />
              <br />
              <a href="https://${dashboard_domain}/web/recovery">https://${dashboard_domain}/web/recovery</a><br />
              <br />
              Nach dem Festlegen eines Passworts finden Sie Ihre Zugriffe unter
              <a href="https://${dashboard_domain}">https://${dashboard_domain}</a><br />
              <br />
              Mit freundlichen Grüßen,<br />
              Ihr Stackspin-Administrator
            plainBody: |-
              Hallo {{ .Identity.traits.name }},

              Bitte klicken Sie auf den folgenden Link, um Ihr Passwort für FTT Forensic Discovery zu ändern:

              {{ .RecoveryURL }}

              Der Link läuft in einer Stunde ab. Sollte er nicht mehr funktionieren, starten Sie einen neuen Kontowiederherstellungsprozess über folgenden Link:

              https://${dashboard_domain}/web/recovery

              Nach dem Festlegen eines Passworts finden Sie Ihre Zugriffe unter
              https://${dashboard_domain}

              Mit freundlichen Grüßen,
              Ihr Stackspin-Administrator
