apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stackspin-apps
  name: stackspin-nextcloud-override
data:
  # https://artifacthub.io/packages/helm/nextcloud/nextcloud#configuration
  values.yaml: |

    nextcloud:
      nextcloud:
        configs:
          # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#user-experience
          #'defaultapp' => 'dashboard,files',
          # https://github.com/moment/moment/tree/2.18.1/locale
          #'default_language' => 'en_de', # https://www.transifex.com/explore/languages/
          #'theme' => 'dark',
          #'logo_url' => 'https://example.org',
          defaults.config.php: |-
            <?php
            $CONFIG = [
              'default_phone_region' => 'DE',
              'default_locale' => 'en-gb',
              'default_timezone' => 'Europe/Berlin',

              'allow_user_to_change_display_name' => false,
              'lost_password_link' => 'https://dashboard.${domain}/web/recovery',
              'simpleSignUpLink.shown' => false,

              'skeletondirectory' => '',
            ];
          previews.config.php: |-
            <?php
            $CONFIG = [
              'enable_previews' => true,
              'enabledPreviewProviders' => [
                  'OC\\Preview\\BMP',
                  'OC\\Preview\\GIF',
                  'OC\\Preview\\JPEG',
                  'OC\\Preview\\Krita',
                  'OC\\Preview\\MarkDown',
                  'OC\\Preview\\MP3',
                  'OC\\Preview\\PNG',
                  'OC\\Preview\\TXT',
                  'OC\\Preview\\XBitmap',

                  'OC\\Preview\\MSOfficeDoc',
                  'OC\\Preview\\MSOffice2003',
                  'OC\\Preview\\MSOffice2007',
                  'OC\\Preview\\OpenDocument',
                  'OC\\Preview\\StarOffice',
                  'OC\\Preview\\EMF',

                  'OC\\Preview\\SVG',
                  'OC\\Preview\\TIFF',
                  'OC\\Preview\\PDF',
                  'OC\\Preview\\Illustrator',
                  'OC\\Preview\\Photoshop',
                  'OC\\Preview\\Postscript',
                  'OC\\Preview\\Font',
                  'OC\\Preview\\HEIC',
                  'OC\\Preview\\TGA',
                  'OC\\Preview\\SGI',

                  'OC\\Preview\\Movie'
                ]
            ];
          # https://help.nextcloud.com/t/preview-settings-not-described-well/197952/9
        extraVolumes:
          - name: nas-media
            nfs:
              server: 172.16.0.2
              path: /mnt/b/media
        extraVolumeMounts:
          - name: nas-media
            mountPath: /var/www/html/data/nfs/nas-media
      #lifecycle:
      #  postStartCommand:
      #    - '/bin/bash'
      #    - '-c'
      #    - '/opt/setup.sh && /var/local/setup-apps.sh'
    apps:
      custom:
        # Basics
        #- name: bruteforcesettings
        #  enabled: false
        #- name: password_policy
        #  enabled: false
        - name: files_external
          enabled: true
        # Common Apps
        #- name: external
        #  enabled: true
        #  github_repository: nextcloud/external
        #  version: "v5.3.1"
        #- name: polls
        #  enabled: false
        #  #unsure - maybe redundant to forms?
        #- name: forms
        #  enabled: true
        #- name: spreed
        #  enabled: false
        # redundant to Zulip & Jitsi
        # Management
        #- name: deck
        #  enabled: true
        #- name: tasks
        #  enabled: true
        # Convenience
        # TODO handy but abendoned - https://apps.nextcloud.com/apps/extract
        #- name: extract
        #  enabled: false
        # Collaborative apps
        #- name: files_markdown
        #  enabled: false
        #- name: files_texteditor
        #  enabled: true
        - name: notes
          enabled: true
        - name: drawio
          enabled: true
          version: "v3.0.3"
          release_filename: "drawio-{{ .version }}.tar.gz"
          github_repository: jgraph/drawio-nextcloud
        # INCOMPATIBLE https://apps.nextcloud.com/apps/files_mindmap
        # name: files_mindmap
        #  enabled: true
        - name: maps
          enabled: true
          version: "1.5.0"
          raw_url: "https://github.com/nextcloud/maps/releases/download/v{{ .version }}/maps-{{ .version }}.tar.gz"
          #release_filename: "maps-{{ .version }}.tar.gz"
          #github_repository: nextcloud/maps
          # waiting for /var/lib/Stackspin/local-storage/pvc-3b008674-544c-46e7-b456-f20932eb9f23_stackspin-apps_nextcloud-files/custom_apps
        # Aesthetics
        #- name: theming
        #  enabled: true
        #- name: apporder
        #  enabled: false
        - name: side_menu
          enabled: true
          version: "v4.0.1"
          raw_url: "https://gitnet.fr/deblan/side_menu/releases/download/{{ .version }}/side_menu_{{ .version }}.tar.gz"
        - name: breezedark
          enabled: false #TEMP
          #version: "v29.0.0"
          #release_filename: "breezedark.tar.gz"
          #github_repository: mwalbeck/nextcloud-breeze-dark
          #raw_url: https://github.com/mwalbeck/nextcloud-breeze-dark/releases/download/v29.0.0/breezedark.tar.gz
          #- name: unsplash
          #  enabled: true
        # Flow
        - name: analytics
          enabled: false #TEMP
          #- name: workflow_pdf_converter
          #  enabled: true
          #- name: files_accesscontrol
          #  enabled: false
          #- name: files_automatedtagging
          #  enabled: false
          #- name: workflow_media_converter
          #  enabled: false
          #- name: workflow_ocr
          #  enabled: false
        # Testing
        #- name: event_update_notification
        #  enabled: false
        - name: google_synchronization
          enabled: false #TEMP
        #- name: calendar_resource_management
        #  enabled: true
        # TODO install via CLI
        # TODO disabling user status, files_comments, support, event_update_notification (Notifications for calendar event updates), bruteforcesettings
        # disable tasks soon
        # configure firstrunwizard
        # preconfigured: share by mail - https://apps.nextcloud.com/apps/socialsharing_email
