---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-suitecrm-values
  namespace: stackspout
data:
  values.yaml: |
    ingress:
      enabled: true
      #annotations:
      #  kubernetes.io/tls-acme: "true"
      hostname: "people.${domain}"
      tls: true
      certManager: true
    suitecrmUsername: "admin"
    suitecrmEmail: "${admin_email}"
    suitecrmPassword: "${suitecrm-password}"
    #existingSecret: stackspin-suitecrm-variables
    mariadb:
      auth:
        password: "${mariadb-password}"
        rootPassword: "${mariadb-root-password}"
    # TODO Adjust OIDC SSO to service
    #    - name: Stackspin
    #      key: "${client_id}"
    #      secret: "${client_secret}"
    #      customAuthUrl: "https://people.${domain}/login/login"
