---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-gitea-values
  namespace: stackspout
data:
  values.yaml: |
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        certmanager.k8s.io/cluster-issuer: letsencrypt-issuer-staging
      hosts:
        - host: "dev.${domain}"
          paths:
             - path: /
               pathType: Prefix
      tls:
        - secretName: gitea-tls
          hosts:
            - "dev.${domain}"
    gitea:
      oauth:
        - name: Stackspin
          provider: "openidConnect"
          key: "${client_id}"
          secret: "${client_secret}"
          autoDiscoverUrl: "https://sso.${domain}/.well-known/openid-configuration"
      config:
        server:
          ROOT_URL: "https://dev.${domain}"
