apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vikunja-oauth-client.yaml
  - vikunja-release.yaml
  - vikunja-values-configmap.yaml
  - vikunja-postgres-pvc.yaml
  - vikunja-files-pvc.yaml
