apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 8gears-n8n
  namespace: flux-system
spec:
  type: "oci"
  interval: 60m
  url: oci://8gears.container-registry.com/library/n8n
