apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zammad.yaml
  - calcom.yaml
  - forgejo.yaml
  - gitea.yaml
  - invoiceninja.yaml
  - robjuz.yaml
  - vikunja.yaml
  - 8gears.yaml
  - minicloudlabs.yaml
  - nemonik.yaml
  #- truecharts.yaml
