apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vikunja
  namespace: flux-system
spec:
  interval: 60m
  type: "oci"
  url: oci://kolaente.dev/vikunja
  #url: https://kolaente.dev/api/packages/vikunja/helm
