apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vikunja
  namespace: flux-system
spec:
  interval: 6m
  url: https://kolaente.dev/xeruf/helm-chart/raw/branch/helm/
