---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-vikunja-values
  namespace: stackspout
data:
  # Defaults: https://github.com/k8s-at-home/charts/blob/master/charts/stable/vikunja/values.yaml
  # Inherits: https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml
  values.yaml: |
    vikunja:
      config: |-
        auth:
          openid:
            # https://vikunja.io/docs/config-options/#openid
            # Example: https://github.com/go-vikunja/api/blob/main/config.yml.sample#L289-L312
            enabled: true
            redirecturl: "https://do.${domain}/auth/openid/"
            providers:
              - name: Stackspin
                authurl: "https://sso.${domain}/"
                clientid: "${client_id}"
                clientsecret: "${client_secret}"
          local:
            enabled: false
    ingress:
      main:
        enabled: true
        primary: false
        annotations:
          kubernetes.io/tls-acme: "true"
          certmanager.k8s.io/cluster-issuer: letsencrypt-issuer-staging
        hosts:
          - host: "do.${domain}"
            paths:
               - path: /
                 pathType: Prefix
        tls:
          - secretName: vikunja
            hosts:
              - "do.${domain}"
    additionalContainers:
      api:
        image: vikunja/api:0.18.1
      frontend:
        image: vikunja/frontend:0.18.2
