apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-gatus-values
  namespace: stackspout
data:
  values.yaml: |
    # https://github.com/minicloudlabs/helm-charts/blob/main/charts/gatus/values.yaml
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts: [ "${gatus_domain}" ]
      tls:
        - secretName: gatus-tls
          hosts:
            - "${gatus_domain}"

    security:
      oidc:
        issuer-url: "https://${hydra_domain}"
        redirect-url: "https://${gatus_domain}/authorization-code/callback"
        client-id: "${client_id}"
        client-secret: "${client_secret}"
        scopes: ["openid"]
        #autoDiscoverUrl: 'https://${hydra_domain}/.well-known/openid-configuration'

    config:
      alerting:
        # https://github.com/TwiN/gatus?tab=readme-ov-file#configuring-email-alerts
        email:
          from: "${outgoing_mail_from_address}"
          username: "${outgoing_mail_smtp_user}"
          password: "${outgoing_mail_smtp_password}"
          host: "${outgoing_mail_smtp_host}"
          port: ${outgoing_mail_smtp_port}
          to: "${outgoing_mail_from_address}"
          client:
            insecure: false
          default-alert:
            enabled: ${outgoing_mail_enabled}
            description: "health check failed"
            send-on-resolved: true
            failure-threshold: 9
            success-threshold: 3
      maintenance:
        enabled: false
        start: 20:00
        duration: 6h
        every: [Saturday, Sunday]
      connectivity:
        checker:
          target: 1.1.1.1:53
          interval: 60s
      ui:
        header: "FTT Monitor"
        title: "FTT Monitoring"
      default-endpoint: &defaults
        group: FTT
        interval: 2m
        conditions:
          - "[STATUS] == 200"
      endpoints:
        - name: "Nextcloud"
          <<: *defaults
          group: "Stackspout"
          url: "https://files.ftt.gmbh"
        - name: "Zulip"
          <<: *defaults
          group: "Stackspout"
          url: "https://chat.ftt.gmbh"
        - name: "Vikunja"
          <<: *defaults
          group: "Stackspout"
          url: "https://do.ftt.gmbh"
        - name: "HedgeDoc"
          <<: *defaults
          group: "Stackspout"
          url: "https://note.ftt.gmbh"
        - name: "InvoiceNinja"
          url: "https://ninja.ftt.gmbh"
          <<: *defaults
          group: "Stackspout"
        - name: "Zammad"
          url: "https://support.ftt.gmbh"
          <<: *defaults
          group: "Stackspout"
        - name: "Forgejo Repositories"
          url: "https://forge.ftt.gmbh"
          <<: *defaults
          group: "Stackspout"
        - name: "NAS"
          url: "https://nas.ftt.gmbh"
          <<: *defaults
          group: "Tooling"
        - name: "FTT Homepage"
          url: "https://ftt.gmbh"
          <<: *defaults
          group: "FTT"
        - name: "FTT Teampage"
          url: "https://ftt.gmbh/team"
          <<: *defaults
          group: "FTT"
        - name: "FTT Teampage EN"
          url: "https://ftt.gmbh/en/team"
          <<: *defaults
          group: "FTT"
        - name: "Main Admin Panel"
          url: "https://main.iridion.it:999"
          <<: *defaults
          group: "Iridion"
        - name: "Second Admin Panel"
          url: "https://ns2.iridion.it:999"
          <<: *defaults
          group: "Iridion"

        - name: "Fossil Repositories"
          url: "https://fossil.ftt.gmbh"
          enabled: false
          <<: *defaults
          group: "Development"
        - name: "Firezone"
          url: "https://fire.ftt.gmbh"
          enabled: false
          <<: *defaults
          group: "Security"
