apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: stackspout
  labels:
    stackspin.net/backupSet: "gatus"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
