apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-gatus-values
  namespace: stackspout
data:
  values.yaml: |
    # https://github.com/minicloudlabs/helm-charts/blob/main/charts/gatus/values.yaml
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts: [ "${gatus_domain}" ]
      tls:
        - secretName: gatus-tls
          hosts:
            - "${gatus_domain}"

    security:
      oidc:
        issuer-url: "https://${hydra_domain}"
        redirect-url: "https://${gatus_domain}/authorization-code/callback"
        client-id: "${client_id}"
        client-secret: "${client_secret}"
        scopes: ["openid"]
        #autoDiscoverUrl: 'https://${hydra_domain}/.well-known/openid-configuration'

    config:
      alerting:
        # https://github.com/TwiN/gatus?tab=readme-ov-file#configuring-email-alerts
        email:
          from: "${outgoing_mail_from_address}"
          username: "${outgoing_mail_smtp_user}"
          password: "${outgoing_mail_smtp_password}"
          host: "${outgoing_mail_smtp_host}"
          port: ${outgoing_mail_smtp_port}
          to: "${outgoing_mail_from_address}"
          client:
            insecure: false
          default-alert:
            enabled: ${outgoing_mail_enabled}
            description: "health check failed"
            send-on-resolved: true
            failure-threshold: 9
            success-threshold: 3
      maintenance:
        enabled: false
        start: 20:00
        duration: 6h
        every: [Saturday, Sunday]
      connectivity:
        checker:
          target: 1.1.1.1:53
          interval: 60s
      ui:
        header: "${org_name} Monitor"
        title: "${org_name} Monitoring"
      default-endpoint: &defaults
        group: FTT
        interval: 2m
        conditions:
          - "[STATUS] == 200"
      endpoints:
        - name: "Nextcloud"
          <<: *defaults
          group: "Stackspout"
          url: "https://files.${domain}/status.php"
        - name: "Zulip"
          <<: *defaults
          group: "Stackspout"
          url: "https://chat.${domain}"
        - name: "Vikunja"
          <<: *defaults
          group: "Stackspout"
          url: "https://do.${domain}"
        - name: "HedgeDoc"
          <<: *defaults
          group: "Stackspout"
          url: "https://note.${domain}"
        - name: "InvoiceNinja"
          url: "https://ninja.${domain}"
          <<: *defaults
          group: "Stackspout"
        - name: "Zammad"
          url: "https://support.${domain}"
          <<: *defaults
          group: "Stackspout"
        - name: "Forgejo Repositories"
          url: "https://forge.${domain}"
          <<: *defaults
          group: "Stackspout"

        - name: "Mailserver STARTTLS"
          url: "starttls://${outgoing_mail_smtp_host}:587"
          <<: *defaults
          interval: 10m
          client:
            timeout: 5s
          conditions:
            - "[CONNECTED] == true"
        - name: "Mailserver TLS"
          url: "tls://${outgoing_mail_smtp_host}:465"
          <<: *defaults
          interval: 10m
          client:
            timeout: 5s
          conditions:
            - "[CONNECTED] == true"

        - name: "FTT Homepage"
          url: "https://${domain}"
          <<: *defaults
          group: "FTT"
        - name: "FTT Teampage"
          url: "https://${domain}/team"
          <<: *defaults
          group: "FTT"
        - name: "FTT Teampage EN"
          url: "https://${domain}/en/team"
          <<: *defaults
          group: "FTT"
        - name: "Main Admin Panel"
          url: "https://main.iridion.it:999"
          <<: *defaults
          group: "Iridion"
        - name: "Second Admin Panel"
          url: "https://ns2.iridion.it:999"
          <<: *defaults
          group: "Iridion"
