---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documenso-postgres
  namespace: stackspout
  labels:
    stackspin.net/backupSet: "documenso"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
