apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-documenso-values
  namespace: stackspout
data:
  values.yaml: |
    global:
      labels:
        stackspin.net/backupSet: "documenso"
    
    podLabels:
      stackspin.net/backupSet: "documenso"
    
    podAnnotations:
      backup.velero.io/backup-volumes: "data"
    
    persistence:
      enabled: true
      existingClaim: "documenso-data"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: "${documenso_domain}"
          paths:
             - path: /
               pathType: Prefix
      tls:
        - secretName: documenso-tls
          hosts:
            - "${documenso_domain}"

    postgresql:
      enabled: true
      commonLabels:
        stackspin.net/backupSet: "documenso"
      global:
        postgresql:
          auth:
            database: documenso
            username: documenso
            password: "${postgresql_password}"
            postgresPassword: "${postgresql_admin_password}"
      primary:
        persistence:
          existingClaim: documenso-postgres
        podAnnotations:
          backup.velero.io/backup-volumes: "data"

    # Mailing configuration
    mailer:
      enabled: "${outgoing_mail_enabled}"
      host: "${outgoing_mail_smtp_host}"
      port: "${outgoing_mail_smtp_port}"
      username: "${outgoing_mail_smtp_user}"
      password: "${outgoing_mail_smtp_password}"
      fromemail: "${outgoing_mail_from_address}"

    # OpenID Connect Single Sign-On Configuration
    auth:
      openid:
        enabled: true
        providers:
          - name: Stackspin
            clientId: "${client_id}"
            clientSecret: "${client_secret}"
            issuer: "https://${hydra_domain}"
            wellKnownUrl: "https://${hydra_domain}/.well-known/openid-configuration"
