apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: suitecrm
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  wait: true
  timeout: 3m
  #dependsOn:
  # - name: single-sign-on
  sourceRef:
    kind: GitRepository
    name: stackspout
  path: ./basic/apps/people
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: stackspin-suitecrm-variables
      #- kind: Secret
      #  name: stackspin-suitecrm-oauth-variables
      - kind: Secret
        name: stackspin-cluster-variables
