apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-invoiceninja-values
  namespace: stackspout
data:
  values.yaml: |
    # https://github.com/invoiceninja/dockerfiles/blob/master/charts/invoiceninja/values.yaml
    ingress:
      enabled: true
      # Elaborate style
      #annotations:
      #  kubernetes.io/tls-acme: "true"
      #hosts:
      #  - host: "ninja.${domain}"
      #    paths:
      #       - path: /
      #         pathType: Prefix
      #tls:
      #  - secretName: invoiceninja-tls
      #    hosts:
      #      - "ninja.${domain}"
      # Bitnami style
      hostname: "ninja.${domain}"
      tls: true
      certManager: true
    persistence:
      public:
        existingClaim: invoiceninja-data
    appKey: "ksickejksickejksickejdddksickejd"
    mariadb:
      # https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml
      auth:
        rootPassword: "testilein"
        password: "bratwurst"
    # TODO Adjust invoiceninja Mailing config
    #    mailer:
    #      enabled: "${outgoing_mail_enabled}"
    #      host: "${outgoing_mail_smtp_host}"
    #      port: "${outgoing_mail_smtp_port}"
    #      username: "${outgoing_mail_smtp_user}"
    #      password: "${outgoing_mail_smtp_password}"
    #      fromemail: "${outgoing_mail_from_address}"
    # TODO Adjust invoiceninja OpenID Connect Single Sign-On Configuration
    #    - name: Stackspin
    #      key: "${client_id}"
    #      secret: "${client_secret}"
    #      autoDiscoverUrl: 'https://sso.${domain}/.well-known/openid-configuration'
