---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 5m
  timeout: 30m
  dependsOn:
    - name: single-sign-on
  sourceRef:
    kind: GitRepository
    name: stackspout
  path: ./basic/apps/gitea
  prune: true
  # TODO what does this mean?
  #validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: gitea
      namespace: stackspout
    - apiVersion: apps/v1
      kind: Deployment
      name: gitea
      namespace: stackspout
  postBuild:
    substituteFrom:
      #- kind: Secret
      #  name: stackspin-gitea-variables
      - kind: Secret
        name: stackspin-gitea-oauth-variables
      - kind: Secret
        name: stackspin-cluster-variables
