apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: custom-infrastructure
  namespace: flux-system
spec:
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: custom-flux-example
  path: ./basic/infrastructure
  prune: true
  validation: client
