apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: stackspin-calcom-keys
  namespace: stackspout
spec:
  # DATABASE_URL
  # NEXT_PUBLIC_WEBAPP_URL
  fields:
  - fieldName: NEXTAUTH_SECRET
  - fieldName: CALENDSO_ENCRYPTION_KEY
