apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-n8n-values
  namespace: stackspout
data:
  values.yaml: |
    # https://github.com/8gears/n8n-helm-chart/blob/master/values.yaml
    image:
      tag: "1.47.3"

    n8n:
      encryption_key: "${encryption_key}"

    commonLabels:
      stackspin.net/backupSet: "n8n"
    podLabels:
      stackspin.net/backupSet: "n8n"
    podAnnotations:
      backup.velero.io/backup-volumes: "data"

    persistence:
      enabled: true
      type: existing
      existingClaim: "n8n-data"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          more_set_headers "Content-Security-Policy: frame-ancestors 'self' files.${domain}";
      hosts:
        - host: "${n8n_domain}"
          paths: [ "/" ]
      tls:
        - secretName: n8n-tls
          hosts:
            - "${n8n_domain}"

    config:
      database:
        type: sqlite
      host: "${n8n_domain}"
      port: 443
      protocol: https
      generic:
        timezone: "Europe/Berlin"
    extraEnv:
      NODE_FUNCTION_ALLOW_EXTERNAL: "*"
      #node-fetch
