apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-vikunja-test-values
  namespace: stackspout
data:
  # Defaults: https://github.com/k8s-at-home/charts/blob/master/charts/stable/vikunja/values.yaml
  # Inherits: https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml
  values.yaml: |
    additionalContainers:
      api:
        image: vikunja/api:0.18.1
        imagePullPolicy: Always
      frontend:
        image: vikunja/frontend:0.18.2
        imagePullPolicy: Always
    vikunja:
      config: |-
        auth:
          openid:
            # https://vikunja.io/docs/config-options/#openid
            # Example: https://github.com/go-vikunja/api/blob/main/config.yml.sample#L289-L312
            enabled: true
            redirecturl: "https://do-test.${domain}/auth/openid/"
            providers:
              - name: Stackspin
                authurl: "https://sso.${domain}/"
                clientid: "${client_id}"
                clientsecret: "${client_secret}"
        service:
          frontendurl: "https://do-test.${domain}"
        database:
          type: postgres
          host: vikunja-test-postgresql
          password: "${postgresql_password}"
        log:
          path: "/app/vikunja"
          http: stdout
          database: stderr
          databaselevel: debug
    ingress:
      main:
        enabled: true
        primary: false
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: "do-test.${domain}"
            paths:
               - path: /
                 pathType: Prefix
        tls:
          - secretName: vikunja-test-tls
            hosts:
              - "do-test.${domain}"
    caddy:
      noTls: true
    postgresql:
      enabled: true
      postgresqlDatabase: vikunja
      postgresqlUsername: vikunja
      postgresqlPassword: "${postgresql_password}"
      persistence:
        enabled: true
        existingClaim: vikunja-test-postgres
