apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-zammad-values
  namespace: stackspout
data:
  values.yaml: |
    # https://github.com/zammad/zammad-helm/blob/main/zammad/values.yaml
    commonLabels:
      stackspin.net/backupSet: "zammad"
    podLabels:
      stackspin.net/backupSet: "zammad"
    podAnnotations:
      backup.velero.io/backup-volumes: "data"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: "${zammad_domain}"
          paths:
             - path: /
               pathType: Prefix
      tls:
        - secretName: zammad-tls
          hosts:
            - "${zammad_domain}"

    zammadConfig:
      minio:
        enabled: false
      postgresql:
        enabled: true
        user: "zammad"
        pass: "${postgresql_password}"
        db: "zammad"
      redis:
        pass: "${redis_password}"

    postgresql:
      # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
      auth:
        username: "zammad"
        database: "zammad"
        postgresPassword: "${postgresql_postgres_password}"
        password: "${postgresql_password}"
      primary:
        persistence:
          existingClaim: zammad-postgres
        podAnnotations:
          backup.velero.io/backup-volumes: "data"

    minio:
      auth:
        rootUser: "zammadadmin"
        rootPasswort: "${minio_password}"

    redis:
      auth:
        password: "${redis_password}"

    persistence:
      enabled: true
      existingClaim: zammad-data

    autoWizard:
      enabled: false

    # TODO Adjust zammad Mailing config
    #    mailer:
    #      enabled: "${outgoing_mail_enabled}"
    #      host: "${outgoing_mail_smtp_host}"
    #      port: "${outgoing_mail_smtp_port}"
    #      username: "${outgoing_mail_smtp_user}"
    #      password: "${outgoing_mail_smtp_password}"
    #      fromemail: "${outgoing_mail_from_address}"
    # TODO Adjust zammad OpenID Connect Single Sign-On Configuration
    #    - name: Stackspin
    #      key: "${client_id}"
    #      secret: "${client_secret}"
    #      autoDiscoverUrl: 'https://${hydra_domain}/.well-known/openid-configuration'
