apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-zammad-values
  namespace: stackspout
data:
  values.yaml: |
    # TODO verify structure matches chart
    ingress:
      enabled: true
      # Elaborate style
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: "support.${domain}"
          paths:
             - path: /
               pathType: Prefix
      tls:
        - secretName: zammad-tls
          hosts:
            - "support.${domain}"
      # Bitnami style
      hostname: "support.${domain}"
      tls: true
      certManager: true
    # TODO Configure PVC for data & database
    # TODO Adjust zammad Mailing config
    #    mailer:
    #      enabled: "${outgoing_mail_enabled}"
    #      host: "${outgoing_mail_smtp_host}"
    #      port: "${outgoing_mail_smtp_port}"
    #      username: "${outgoing_mail_smtp_user}"
    #      password: "${outgoing_mail_smtp_password}"
    #      fromemail: "${outgoing_mail_from_address}"
    # TODO Adjust zammad OpenID Connect Single Sign-On Configuration
    #    - name: Stackspin
    #      key: "${client_id}"
    #      secret: "${client_secret}"
    #      autoDiscoverUrl: 'https://sso.${domain}/.well-known/openid-configuration'
