apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-gitea-values
  namespace: stackspout
data:
  values.yaml: |
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      hosts:
        - host: "code.${domain}"
          paths:
             - path: /
               pathType: Prefix
      tls:
        - secretName: gitea-tls
          hosts:
            - "code.${domain}"
    gitea:
      oauth:
        - name: Stackspin
          provider: "openidConnect"
          key: "${client_id}"
          secret: "${client_secret}"
          autoDiscoverUrl: "https://sso.${domain}/.well-known/openid-configuration"
      config:
        server:
          ROOT_URL: "https://code.${domain}"
          # START_SSH_SERVER: true
        service:
          DISABLE_REGISTRATION: true
        log:
          LEVEL: "Trace"
    persistence:
      enabled: true
      existingClaim: gitea-data
    postgresql:
      persistence:
        enabled: true
        existingClaim: gitea-postgres
