apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  wait: true
  timeout: 3m
  dependsOn:
    - name: single-sign-on
  sourceRef:
    kind: GitRepository
    name: stackspout
  path: ./apps/forge
  prune: true
  postBuild:
    substituteFrom:
      #- kind: Secret
      #  name: stackspin-forgejo-variables
      - kind: Secret
        name: stackspin-forgejo-oauth-variables
      - kind: Secret
        name: stackspin-cluster-variables
