apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ninja-kustomization.yaml
  - do-kustomization.yaml
  - forge-kustomization.yaml
  - support-kustomization.yaml
  - flow-kustomization.yaml
  - meet-kustomization.yaml
  - status-kustomization.yaml
  - board-kustomization.yaml
  - design-kustomization.yaml
  #- sign-kustomization.yaml
  #- stirling-kustomization.yaml
  #- sprint-kustomization.yaml #charts outdated
  #- video-kustomization.yaml #missing storage
