apiVersion: v1
kind: Secret
metadata:
  name: stackspin-calcom-keys
  namespace: stackspout
stringData:
  DATABASE_URL: "postgresql://calcom:${postgresql_password}@calcom-postgresql/calcom"
  #ALLOWED_HOSTNAMES: '"${calcom_domain}"'
  NEXT_PUBLIC_WEBAPP_URL: "https://${calcom_domain}"
  #NEXT_PUBLIC_API_V2_URL: "https://${calcom_domain}/api/v2"
  NEXTAUTH_SECRET: "${nextauth_secret}"
  CALENDSO_ENCRYPTION_KEY: "${calendso_key}"
  EMAIL_FROM: "${outgoing_mail_from_address}"
  #EMAIL_FROM_NAME: "${org_name}"
  EMAIL_SERVER_HOST: "${outgoing_mail_smtp_host}"
  EMAIL_SERVER_PORT: ${quote}${outgoing_mail_smtp_port}${quote}
  EMAIL_SERVER_USER: "${outgoing_mail_smtp_user}"
  EMAIL_SERVER_PASSWORD: "${outgoing_mail_smtp_password}"
  # email_enabled: "${outgoing_mail_enabled}"
