apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: invoiceninja
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  wait: true
  timeout: 3m
  #dependsOn:
  #  - name: single-sign-on
  sourceRef:
    kind: GitRepository
    name: stackspout
  path: ./apps/ninja
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: stackspin-invoiceninja-variables
      - kind: Secret
        name: stackspin-invoiceninja-oauth-variables
        optional: true
      - kind: Secret
        name: stackspin-cluster-variables
      - kind: ConfigMap
        name: stackspin-nextcloud-kustomization-variables
