apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stackspin
  name: stackspin-nginx-override
data:
  values.yaml: |
    # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
    controller:
      image:
        registry: "k8s.gcr.io"
    controller:
      admissionWebhooks:
        patch:
          image:
            registry: "k8s.gcr.io"
