---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stackspin-apps
  name: stackspin-zulip-override
data:
  values.yaml: |
    zulip:
      environment:
        SETTING_AUTHENTICATION_BACKENDS: '("zproject.backends.GenericOpenIdConnectBackend","EmailAuthBackend")'
