---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stackspin-apps
  name: stackspin-nextcloud-override
data:
  values.yaml: |
    apps:
      # Basics
      - name: photos
        enabled: false
      - name: contacts
        enabled: true
      # Common Apps
      - name: external
        enabled: true
      - name: polls
        enabled: false
        #unsure - maybe redundant to forms?
      - name: forms
        enabled: true
      - name: spreed
        enabled: false
        # redundant to Zulip & Jitsi
      - name: appointments
        enabled: true
      # Management
      - name: deck
        enabled: true
      - name: tasks
        enabled: true
      # Convenience
      - name: files_rightclick
        enabled: true
      - name: metadata
        enabled: true
      - name: extract
        enabled: true
      # Collaborative apps
      - name: drawio
        enabled: false
        #buggy
      - name: notes
        enabled: true
      - name: files_mindmap
        enabled: false
        #buggy
      - name: files_markdown
        enabled: true
      - name: files_texteditor
        enabled: true
      - name: maps
        enabled: true
      - name: jitsi
        enabled: true
      # Aesthetics
      - name: theming
        enabled: true
      - name: apporder
        enabled: true
      - name: side_menu
        enabled: true
      - name: breezedark
        enabled: true
      - name: unsplash
        enabled: true
