---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stackspin-gitea-values
  namespace: stackspout
data:
  values.yaml: |
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: "dev.ftt.gmbh"
          paths:
             - path: /
               pathType: Prefix
      tls:
        - secretName: gitea-tls
          hosts:
            - "dev.ftt.gmbh"
    gitea:
      oauth:
        - name: Stackspin
          provider: 'openidConnect'
          key: "${client_id}"
          secret: "${client_secret}"
          customAuthUrl: "https://sso.ftt.gmbh"
          #autoDiscoverUrl: 'https://gitea.example.com/.well-known/openid-configuration'
